name: "Wush Remote Access"

on:
  workflow_dispatch:    # یعنی با زدن دکمه "Run workflow" در گیتهاب، این کار اجرا شود

jobs:
  wush:
    runs-on: ubuntu-latest
    steps:
      - name: Start Wush Session
        uses: coder/wush-action@v1.0.0
        timeout-minutes: 30   # یعنی این اتصال 30 دقیقه باز می‌ماند
